const effectPedals = [
  {
    pedalName: "Utopia Analog Delay",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Delay",
    additionalCategory: "Modulation",
    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 290,
    width: 6.4,
    height: 5.9,
    depth: 11.8,
  },
  {
    pedalName: "#1echo",
    manufacturer: "Electro-Harmonix",
    madeIn: "USA",
    category: "Delay",
    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    weight: 450,
    width: 10.2,
    height: 8.9,
    depth: 12.1,
  },
  {
    pedalName: "3699 Fuzz",
    manufacturer: "Danelectro",
    madeIn: "China",
    category: "Fuzz",
    additionalCategory: "Octaver",
    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 270,
    inspiredBy: "FOXX Tone Machine",
    width: 5.8,
    height: 5.8,
    depth: 11.5,
  },

  {
    pedalName: "Back Talk",
    manufacturer: "Danelectro",
    madeIn: "China",
    category: "Delay",
    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 250,
    specialFeatures: "Reverse Delay",
    width: 5.8,
    height: 5.8,
    depth: 11.5,
  },

  {
    pedalName: "385 Overdrive",
    manufacturer: "Walrus Audio",
    madeIn: "USA",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 270,
    inspiredBy: "385 Bell & Howell Projector",
    width: 6.6,
    height: 5.8,
    depth: 12.1,
  },
  {
    pedalName: "DRV No3",
    manufacturer: "1981 Inventions",
    madeIn: "USA",
    category: "Distortion",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 400,
    inspiredBy: "ProCo RAT",
    width: 8.6,
    height: 4.6,
    depth: 10.7,
  },
  {
    pedalName: "Cinnamon Drive",
    manufacturer: "Aclam",
    madeIn: "Spain",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 410,
    width: 13.6,
    height: 5.5,
    depth: 8.7,
  },
  {
    pedalName: "Dr. Robert",
    manufacturer: "Aclam",
    madeIn: "Spain",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 410,
    inspiredBy: "Vox UL730",
    specialFeatures: "Bass and Guitar Pedal",
    width: 13.6,
    height: 5.5,
    depth: 8.7,
  },
  {
    pedalName: "The Woman Tone",
    manufacturer: "Aclam",
    madeIn: "Spain",
    year: "2020's",
    category: "Overdrive",
    additionalCategory: "Boost",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 420,
    specialFeatures: "Pickup Simulator",
    width: 13.7,
    height: 5.5,
    depth: 8.8,
  },
  {
    pedalName: "The Windmiller",
    manufacturer: "Aclam",
    madeIn: "Spain",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 450,
    inspiredBy: "Grampian 636 Spring Reverb Pre Amp",
    width: 13.6,
    height: 5.5,
    depth: 8.7,
  },

  {
    pedalName: "Agro",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 480,
    width: 6.8,
    height: 5.3,
    depth: 11.3,
  },
  {
    pedalName: "Chorusaurus",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Chorus",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 480,
    width: 6.8,
    height: 5.3,
    depth: 13.3,
  },
  {
    pedalName: "Filter Twin",
    manufacturer: "Aguilar",
    madeIn: "USA",
    year: "2000s",
    category: "Envelope Filter",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 490,
    width: 6.8,
    height: 13.3,
    depth: 5.3,
  },

  {
    pedalName: "Fuzzistor",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 480,
    width: 6.8,
    height: 5.3,
    depth: 13.3,
  },
  {
    pedalName: "Grape Phaser",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Phaser",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 290,
    width: 6.8,
    height: 5.3,
    depth: 13.3,
  },
  {
    pedalName: "Octamizer",
    manufacturer: "Aguilar",
    madeIn: "USA",
    year: "2000s",
    category: "Octaver",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 490,
    width: 6.8,
    height: 13.3,
    depth: 5.3,
  },
  {
    pedalName: "TLC Compressor",
    manufacturer: "Aguilar",
    madeIn: "USA",
    year: "2000s",
    category: "Compressor",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 490,
    width: 6.8,
    height: 13.3,
    depth: 5.3,
  },
  {
    pedalName: "The Windmiller",
    manufacturer: "Aclam",
    madeIn: "Spain",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 450,
    inspiredBy: "Grampian 636 Spring Reverb Pre Amp",
    width: 13.6,
    height: 5.5,
    depth: 8.7,
  },
  {
    pedalName: "Agro",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 480,
    width: 6.8,
    height: 5.3,
    depth: 11.3,
  },
  {
    pedalName: "Chorusaurus",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Chorus",
    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 480,
    width: 6.8,
    height: 5.3,
    depth: 13.3,
  },
  {
    pedalName: "Filter Twin",
    manufacturer: "Aguilar",
    madeIn: "USA",
    year: "2000s",
    category: "Envelope Filter",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 490,
    width: 6.8,
    height: 13.3,
    depth: 5.3,
  },
  {
    pedalName: "Fuzzistor",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 480,
    width: 6.8,
    height: 5.3,
    depth: 13.3,
  },
  {
    pedalName: "Grape Phaser",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Phaser",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 290,

    width: 6.8,
    height: 5.3,
    depth: 13.3,
  },
  {
    pedalName: "Octamizer",
    manufacturer: "Aguilar",
    madeIn: "USA",
    year: "2000s",
    category: "Octaver",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 490,
    width: 6.8,
    height: 13.3,
    depth: 5.3,
  },
  {
    pedalName: "TLC Compressor",
    manufacturer: "Aguilar",
    madeIn: "USA",
    year: "2000s",
    category: "Compressor",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 490,
    width: 6.8,
    height: 13.3,
    depth: 5.3,
  },
  {
    pedalName: "Alien Comp",
    manufacturer: "Analog Alien",
    madeIn: "USA",
    category: "Compressor",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 10,
    height: 5.8,
    depth: 12.2,
  },
  {
    pedalName: "Alien Twister",
    manufacturer: "Analog Alien",
    madeIn: "USA",
    category: "Buffer, Fuzz",

    jacksMountedOn: "Sides",
    bypass: "selectable",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 10.9,
    height: 6.1,
    depth: 5.3,
  },
  {
    pedalName: "Bucket Seat",
    manufacturer: "Analog Alien",
    madeIn: "USA",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 10,
    height: 5.8,
    depth: 12.2,
  },
  {
    pedalName: "Fuzz Bubble 45",
    manufacturer: "Analog Alien",
    madeIn: "USA",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 500,
    width: 12.6,
    height: 9.5,
    depth: 5.5,
  },
  {
    pedalName: "Joe Walsh Double Classic",
    manufacturer: "Analog Alien",
    madeIn: "USA",
    category: "Compressor, Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 800,
    width: 14.6,
    height: 3.8,
    depth: 12,
  },
  {
    pedalName: "Power Pack",
    manufacturer: "Analog Alien",
    madeIn: "USA",
    category: "Boost",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 6.6,
    height: 3.5,
    depth: 12.1,
  },
  {
    pedalName: "Rumble Seat",
    manufacturer: "Analog Alien",
    madeIn: "USA",
    category: "Delay, Overdrive, Reverb",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 800,
    width: 14.6,
    height: 3.8,
    depth: 12,
  },
  {
    pedalName: "Ages",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Tremolo",
    additionalCategory: "Harmonic Tremolo",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 500,
    specialFeatures: "Spinner Expression Pedal",
    width: 12,
    height: 8,
    depth: 16,
  },
  {
    pedalName: "Bitoun Fuzz",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 280,
    specialFeatures: "Dip Switches",
    width: 6.6,
    height: 5.9,
    depth: 12,
  },
  {
    pedalName: "Bitoun Fuzz",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 280,
    specialFeatures: "Dip Switches",
    width: 6.6,
    height: 5.9,
    depth: 12,
  },

  {
    pedalName: "Element",
    manufacturer: "Anasounds",
    series: "Elements",
    madeIn: "France",
    category: "Reverb",
    additionalCategory: "Drive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 290,
    inspiredBy: "Fender Twin Reverb",
    specialFeatures: "Switchable reverb tanks",
    width: 6.4,
    height: 5.9,
    depth: 11.8,
  },
  {
    pedalName: "High voltage",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 290,
    specialFeatures: "Bass Cut",
    width: 12,
    height: 8,
    depth: 16,
  },

  {
    pedalName: "Savage",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 430,
    width: 6,
    height: 4,
    depth: 12,
  },

  {
    pedalName: "Tremolo",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Tremolo",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 500,
    specialFeatures: "Spinner Expression Pedal",
    width: 12,
    height: 8,
    depth: 16,
  },

  {
    pedalName: "PRO FF Sub Harmonic Generator",
    manufacturer: "Ashdown",
    series: "Pro category",
    madeIn: "China",
    category: "Octaver",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 600,
    width: 7.3,
    height: 4.5,
    depth: 11.6,
  },

  {
    pedalName: "PRO category Double Shot",
    manufacturer: "Ashdown",
    series: "Pro category",
    madeIn: "China",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 600,
    width: 7.3,
    height: 4.5,
    depth: 11.6,
  },
  {
    pedalName: "Fatbee Overdrive",
    manufacturer: "Beetronics",
    series: "Babee",
    madeIn: "USA",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 230,
    width: 5.7,
    height: 3.5,
    depth: 11.4,
  },
  {
    pedalName: "Vezzpa",
    manufacturer: "Beetronics",
    madeIn: "USA",
    category: "Fuzz",
    additionalCategory: "Octaver",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 320,
    width: 6.3,
    height: 5.7,
    depth: 11.4,
  },
  {
    pedalName: "HT-Drive",
    manufacturer: "Blackstar Amplification",
    series: "HT Pedals",
    madeIn: "China",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 1200,
    width: 16,
    height: 8,
    depth: 12,
  },
  {
    pedalName: "HM300 Heavy Metal",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 300,
    inspiredBy: "BOSS HM-2",
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },
  {
    pedalName: "OD300 Overdrive Distortion",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Overdrive",
    additionalCategory: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 300,
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },
  {
    pedalName: "SF300 Super Fuzz",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Fuzz",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 300,
    inspiredBy: "BOSS FZ-2",
    specialFeatures: "Secret Mode",
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },
  {
    pedalName: "TM300 Tube Amp Modeler",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Amp Modeler",

    jacksMountedOn: "Sides",

    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 300,
    inspiredBy: "Tech 21 GT2",
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },
  {
    pedalName: "TO800 Vintage Tube Overdrive",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 300,
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },
  {
    pedalName: "UC200 Ultra Chorus",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Chorus",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 300,
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },
  {
    pedalName: "UM300 Ultra Metal",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 300,
    inspiredBy: "BOSS MT-2",
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },
  {
    pedalName: "UV300 Ultra Vibrato",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Vibrato",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 300,
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },
  {
    pedalName: "AC-3 Acoustic Simulator",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Acoustic Simulator",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 440,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "AW-3 Dynamic Wah",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Wah",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 420,
    specialFeatures: "Talking Wah effect",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "BB-1X Bass Driver",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 450,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "BC-1X Bass Comp",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Compressor",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 450,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "BD-2 Blues Driver",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 360,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "BD-2W Blues Driver",
    manufacturer: "BOSS",
    series: "WAZA CRAFT",
    madeIn: "Taiwan",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 430,
    inspiredBy: "BOSS BD-2",

    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "BF-3 Flanger",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Flanger",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 420,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "CE-2 Chorus Ensemble",
    manufacturer: "BOSS",
    madeIn: "Japan",
    year: "1977",
    category: "Chorus",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 450,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "CE-2W Chorus",
    manufacturer: "BOSS",
    series: "WAZA CRAFT",
    madeIn: "Taiwan",
    category: "Chorus",
    additionalCategory: "Vibrato",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 450,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "CE-5 Chorus Ensemble",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Chorus",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 410,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "CEB-3 Bass Chorus",
    manufacturer: "BOSS",
    series: "Compact series",
    madeIn: "Taiwan",
    category: "Chorus",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 450,

    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "CH-1 Super Chorus",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Chorus",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 400,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "CP-1X Compressor",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Compressor",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 450,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "CS-3 Compression Sustainer",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Compressor",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DC-2W Dimension C",
    manufacturer: "BOSS",
    series: "WAZA CRAFT",
    madeIn: "Taiwan",
    category: "Chorus",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 450,
    inspiredBy: "BOSS DC-2, Roland SDD-320",
    specialFeatures: "Stereo Input & Output",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DD-3 Digital Delay",
    manufacturer: "BOSS",
    series: "Digital Delay series",
    madeIn: "Taiwan",
    year: "1986-2019",
    category: "Delay",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 460,

    specialFeatures: "Hold function",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DD-3T Digital Delay",
    manufacturer: "BOSS",
    series: "Compact",
    madeIn: "Malaysia",
    category: "Delay",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 420,
    inspiredBy: "DD-3",

    specialFeatures: "Tap Tempo",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DD-7 Digital Delay",
    manufacturer: "BOSS",
    series: "Digital Delay series",
    madeIn: "Taiwan",
    category: "Delay",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 440,
    specialFeatures: "Hold Function",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DD-8 Digital Delay",
    manufacturer: "BOSS",
    series: "Compact",
    madeIn: "Malaysia",
    category: "Delay",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 440,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DM-2 Delay",
    manufacturer: "BOSS",
    series: "Compact",
    madeIn: "Japan",
    category: "Delay",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 460,

    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DM-2W Delay",
    manufacturer: "BOSS",
    series: "WAZA CRAFT",
    madeIn: "Taiwan",
    category: "Delay",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 460,
    inspiredBy: "BOSS DM-2",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DS-1 (Vintage)",
    manufacturer: "BOSS",
    madeIn: "Japan",
    series: "Compact",
    year: "1979",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,

    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DS-1 Distortion",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,

    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DS-1W",
    manufacturer: "BOSS",
    madeIn: "Japan",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    inspiredBy: "DS-1",
    width: 6.4,
    height: 5.1,
    depth: 11.9,
  },
  {
    pedalName: "DS-1X Distortion",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 450,
    specialFeatures: "MDP",
    width: 7.2,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DS-2 Turbo Distortion",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    inspiredBy: "DS-1",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "FZ-1w",
    manufacturer: "BOSS",
    madeIn: "Japan",
    category: "Fuzz",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 440,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "FZ-5 Fuzz",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Fuzz",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 440,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "HM-2",
    manufacturer: "BOSS",
    madeIn: "Japan",
    series: "Compact",
    year: "1990s",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,

    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "HM-2W",
    manufacturer: "BOSS",
    madeIn: "Japan",
    series: "WAZA CRAFT",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 440,
    inspiredBy: "HM-2",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "JB-2 Angry Driver",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",
    additionalCategory: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 440,
    inspiredBy: "BOSS BD-2, JHS Angry Charlie",
    specialFeatures: "Order swapping - Remote Switching",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "MD-2 Mega Distortion",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 410,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "ML-2 Metal Core",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 440,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "MO-2 Multi Overtone",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overtone Generator",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 430,
    width: 7,
    height: 5.5,
    depth: 12.5,
  },

  {
    pedalName: "MT-2 Metal Zone",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 410,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "MT-2W Metal Zone",
    manufacturer: "BOSS",
    series: "WAZA CRAFT",
    madeIn: "Japan",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 410,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "OC-3 Super Octave",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Octaver",
    additionalCategory: "Poly Octave/OC-2 Mode",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 440,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "OC-5",
    manufacturer: "BOSS",
    series: "Compact",
    madeIn: "Taiwan",
    category: "Octaver",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    weight: 440,
    inspiredBy: "BOSS OC-2",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "OD-1 (1984)",
    manufacturer: "BOSS",
    series: "Compact",
    madeIn: "Japan",
    year: 1984,
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 7.9,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "OD-1X Overdrive",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 450,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "OD-3 OverDrive",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 410,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "OD-1X Overdrive",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 450,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "ODB-3 Bass OverDrive",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 420,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "OS-2 Overdrive/Distortion",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",
    additionalCategory: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "PH-1 Phaser (1979)",
    manufacturer: "BOSS",
    madeIn: "Japan",
    year: 1979,
    category: "Phaser",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "PH-3 Phase Shifter",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Phaser",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 420,
    inspiredBy: "BOSS PH-1",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "PS-6 Harmonist",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Pitch Shifter",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 440,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "RE-2",
    manufacturer: "BOSS",
    series: "Compact",
    madeIn: "Malaysia",
    year: 2022,
    category: "Delay",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 4500,
    inspiredBy: "RE:201 Space Echo",
    specialFeatures: "Carry Over Switch",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "RE-20 Space Echo",
    manufacturer: "BOSS",
    series: "20",
    madeIn: "Taiwan",
    category: "Delay",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 1100,
    inspiredBy: "RE:201 Space Echo",
    width: 17.3,
    height: 5.7,
    depth: 15.8,
  },

  {
    pedalName: "SY-1",
    manufacturer: "BOSS",
    madeIn: "Malaysia",
    category: "Synthesizer",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 450,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "RV-6 Reverb",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Reverb",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 450,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "SD-1 Super Overdrive",
    manufacturer: "BOSS",
    madeIn: "Taiwan",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "SD-1W Super Overdrive",
    manufacturer: "BOSS",
    series: "WAZA CRAFT",
    madeIn: "Taiwan",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 430,
    inspiredBy: "BOSS SD-1",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "SL-2 Slicer",
    manufacturer: "BOSS",
    madeIn: "Japan",
    year: "2020's",
    category: "Beat Generator",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    color: "Green",
    weight: 400,
    inspiredBy: "BOSS SL-20",
    width: 6.4,
    height: 5.1,
    depth: 11.9,
  },
  {
    pedalName: "ST-2 Power Stack",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",
    additionalCategory: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 440,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "TB-2W",
    manufacturer: "BOSS",
    madeIn: "Japan",
    category: "Fuzz",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: "7, 9, 12",
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 440,
    inspiredBy: "ToneBender",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "TE-2 Tera Echo",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Delay",
    additionalCategory: "Ambient",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 430,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "TR-2 Tremolo",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Tremolo",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 400,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "VB-2W Vibrato",
    manufacturer: "BOSS",
    series: "WAZA CRAFT",
    madeIn: "Taiwan",
    category: "Vibrato",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 450,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "Classic Chorus",
    manufacturer: "Carl Martin",
    series: "Vintage series",
    madeIn: "China",
    category: "Chorus",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 350,
    width: 9.5,
    height: 5.6,
    depth: 12,
  },
  {
    pedalName: "Classic Flanger",
    manufacturer: "Carl Martin",
    series: "Vintage series",
    madeIn: "China",
    category: "Flanger",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Hybrid",

    weight: 350,
    width: 9.5,
    height: 5.6,
    depth: 12,
  },
  {
    pedalName: "Classic Opto Compressor",
    manufacturer: "Carl Martin",
    series: "Vintage series",
    madeIn: "China",
    category: "Compressor",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 350,
    width: 9.5,
    height: 5.6,
    depth: 12,
  },
  {
    pedalName: "DC Drive",
    manufacturer: "Carl Martin",
    series: "Vintage series",
    madeIn: "China",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 350,
    specialFeatures: "Reg-Fat switch for gain variety",
    width: 6,
    height: 5,
    depth: 11.5,
  },
  {
    pedalName: "Headroom",
    manufacturer: "Carl Martin",
    series: "Vintage series",
    madeIn: "Denmark",
    category: "Reverb",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 1200,
    width: 26,
    height: 7.1,
    depth: 15,
  },
  {
    pedalName: "Ottawa",
    manufacturer: "Carl Martin",
    series: "Vintage series",
    madeIn: "China",
    category: "Auto Wah",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 340,
    width: 6,
    height: 5,
    depth: 11.5,
  },
  {
    pedalName: "Panama",
    manufacturer: "Carl Martin",
    series: "Vintage series",
    madeIn: "China",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 340,
    width: 6,
    height: 5,
    depth: 11.5,
  },
  {
    pedalName: "PlexiRanger",
    manufacturer: "Carl Martin",
    madeIn: "China",
    category: "Overdrive",
    additionalCategory: "Treble Booster",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    inspiredBy: "Range Master",
    width: 10,
    height: 5.8,
    depth: 12.2,
  },
  {
    pedalName: "PlexiTone Lo Gain",
    manufacturer: "Carl Martin",
    series: "Pro-series",
    madeIn: "China",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    circuit: "Analog",

    weight: 280,
    inspiredBy: "Carl Martin PlexiTone",
    width: 7.2,
    height: 5.7,
    depth: 11.2,
  },
  {
    pedalName: "Purple Moon",
    manufacturer: "Carl Martin",
    series: "Vintage series",
    madeIn: "China",
    category: "Vibe",
    additionalCategory: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 350,
    specialFeatures: "Optional Fuzz added to the circuit",
    width: 6,
    height: 5,
    depth: 11.5,
  },
  {
    pedalName: "Red Repeat",
    manufacturer: "Carl Martin",
    series: "Vintage series",
    madeIn: "Denmark",
    category: "Delay",
    additionalCategory: "Acoustic Simulator",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Hybrid",

    weight: 350,
    width: 9.5,
    height: 5.6,
    depth: 12,
  },
  {
    pedalName: "single Channel AC Tone",
    manufacturer: "Carl Martin",
    series: "Pro-series",
    madeIn: "China",
    year: "2010s",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 280,
    inspiredBy: "Carl Martin AC Tone",
    specialFeatures: "Active Buffered bypass",
    width: 7.2,
    height: 5.7,
    depth: 11.2,
  },
  {
    pedalName: "Surf Trem",
    manufacturer: "Carl Martin",
    series: "Vintage series",
    madeIn: "China",
    category: "Tremolo",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 350,
    width: 6,
    height: 5,
    depth: 11.5,
  },
  {
    pedalName: "Tube Driver (1988)",
    manufacturer: "Chandler Industries",
    madeIn: "USA",
    year: 1988,
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 12,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 1000,
    inspiredBy: "B.K Butler Tube Driver",
    width: 10.5,
    height: 9,
    depth: 17.1,
  },
  {
    pedalName: "Supa Tonebender (1974)",
    manufacturer: "Colorsound",
    madeIn: "UK",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 650,
    inspiredBy: "Electro Harmonix Ram's Head Big Muff",

    width: 12,
    height: 4.2,
    depth: 22,
  },
  {
    pedalName: "Alpha Omicron",
    manufacturer: "Darkglass Electronics",
    madeIn: "Finland",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 250,
    inspiredBy: "Darkglass Alpha · Omega",
    width: 7.5,
    height: 4.5,
    depth: 11.3,
  },
  {
    pedalName: "Microtubes B3K V2",
    manufacturer: "Darkglass Electronics",
    madeIn: "Finland",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 290,
    width: 7.5,
    height: 4.5,
    depth: 11.3,
  },
  {
    pedalName: "Vintage Microtubes",
    manufacturer: "Darkglass Electronics",
    madeIn: "Finland",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 250,
    width: 7.5,
    height: 4.5,
    depth: 11.3,
  },
  {
    pedalName: "Fuzz War",
    manufacturer: "Death By Audio",
    madeIn: "USA",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 540,
    width: 11.8,
    height: 6.2,
    depth: 14.4,
  },
  {
    pedalName: "Germanium Filter",
    manufacturer: "Death By Audio",
    madeIn: "USA",
    year: "2020's",
    category: "Filter",
    additionalCategory: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 300,
    width: 6.4,
    height: 5.7,
    depth: 12.7,
  },
  {
    pedalName: "CPR1 Compressor",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Compressor",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    specialFeatures: "EQ control for overall frequency balance shifting",
    width: 9.8,
    height: 5.4,
    depth: 11.9,
  },
  {
    pedalName: "F-Octave",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Fuzz",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    inspiredBy: "Foxx Tone Machine",
    width: 6.5,
    height: 5.1,
    depth: 12,
  },
  {
    pedalName: "FBR2 Fireburst",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Fuzz",
    additionalCategory: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 350,
    width: 6.5,
    height: 5.1,
    depth: 12,
  },
  {
    pedalName: "HCH1 Halo Chorus",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Chorus",
    additionalCategory: "Delay/Pitch",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Positive",
    circuit: "Analog",

    weight: 450,
    width: 12,
    height: 5.4,
    depth: 12,
    specialFeatures:
      "Autoconfigurable I/O for mono, mono in/stereo out, and stereo in/stereo out operation.",
  },
  {
    pedalName: "JDR3 J-Drive Mk3",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Overdrive",
    additionalCategory: "Boost",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 11.9,
    height: 5.1,
    depth: 9.3,
  },
  {
    pedalName: "MLNJr Memory Lane Jr",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Delay",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Hybrid",

    weight: 420,
    width: 11.9,
    height: 5.1,
    depth: 9.3,
    specialFeatures: "Tap tempo",
  },
  {
    pedalName: "Nine Zero Two",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    year: "2010s",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 350,
    width: 6.4,
    height: 6.1,
    depth: 12.3,
  },
  {
    pedalName: "TRM1 Tremolo",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Tremolo",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 450,
    specialFeatures:
      "Tap tempo and footswitchable double speed mode, User selectable waveforms (sharkfin, sinewave, square wave and chop)",
    width: 11.9,
    height: 5.1,
    depth: 9.3,
  },
  {
    pedalName: "VIB1 Vibrato",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Vibrato",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Positive",
    circuit: "Analog",

    weight: 480,
    width: 12,
    height: 5.4,
    depth: 12,
  },
  {
    pedalName: "Carcosa Fuzz",
    series: "Compact",
    manufacturer: "DOD",
    madeIn: "China",
    category: "Fuzz",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 450,
    width: 6.7,
    height: 5.7,
    depth: 11.9,
  },
  {
    pedalName: "Overdrive Preamp 250",
    year: 1979,
    manufacturer: "DOD",
    madeIn: "USA",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 280,

    width: 6.6,
    height: 5.7,
    depth: 11.8,
  },
  {
    pedalName: "Vibe Machine",
    manufacturer: "Drybell",
    madeIn: "Croatia",
    category: "Vibe",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 280,

    width: 6,
    height: 3.1,
    depth: 11.2,
  },
  {
    pedalName: "Band of Gypsys Fuzz Face Mini Distortion",
    manufacturer: "Dunlop Electronics",
    series: "Authentic Hendrix",
    madeIn: "USA",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 230,
    inspiredBy: "Tycobrahe Octavia",
    width: 8.9,
    height: 5,
    depth: 8.9,
  },
  {
    pedalName: "Germanium Fuzz Face Mini Distortion",
    manufacturer: "Dunlop Electronics",
    madeIn: "USA",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 200,
    width: 8.9,
    height: 5,
    depth: 8.9,
  },
  {
    pedalName: "Jimi Hendrix Fuzz Face Distortion",
    manufacturer: "Dunlop Electronics",
    series: "Authentic Hendrix",
    madeIn: "USA",
    category: "Fuzz",
    additionalCategory: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 350,
    width: 6,
    height: 5,
    depth: 11,
    inspiredBy: "Dallas Arbiter Fuzz Face",
  },
  {
    pedalName: "Jimi Hendrix Fuzz Face Mini Distortion",
    manufacturer: "Dunlop Electronics",
    series: "Authentic Hendrix",
    madeIn: "USA",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 230,
    width: 8.9,
    height: 5,
    depth: 8.9,
    inspiredBy: "Dunlop Electronics JHF-1",
  },
  {
    pedalName: "Silicon Fuzz Face Mini Distortion",
    manufacturer: "Dunlop Electronics",
    madeIn: "USA",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 200,
    width: 8.9,
    height: 5,
    depth: 8.9,
    inspiredBy: "Fuzz Face",
  },
  {
    pedalName: "Brute Drive",
    manufacturer: "E.W.S",
    madeIn: "Japan",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 240,
    specialFeatures: "Boost Switch",
    width: 11.2,
    height: 5,
    depth: 6.5,
  },
  {
    pedalName: "Acapulco Gold",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 2400,
    inspiredBy: "Sunn Model T",
    width: 6.3,
    height: 5.7,
    depth: 11.7,
  },
  {
    pedalName: "Afterneath V3",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Reverb",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 400,
    width: 6.4,
    height: 5.7,
    depth: 12.1,
  },
  {
    pedalName: "Bellows",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    year: "2018-2021",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 250,
    width: 6.4,
    height: 5.7,
    depth: 11.7,
  },
  {
    pedalName: "Bit Commander V2",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Synth",
    additionalCategory: "Octaver",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 6.4,
    height: 5.7,
    depth: 11.7,
  },
  {
    pedalName: "Dispatch Master",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Delay",
    additionalCategory: "Reverb",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 250,
    width: 6.4,
    height: 5.7,
    depth: 11.7,
  },
  {
    pedalName: "Erupter",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 260,
    width: 6.4,
    height: 5.7,
    depth: 11.7,
  },
  {
    pedalName: "Ghost Echo V3",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Reverb",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",

    weight: 270,
    width: 6.4,
    height: 5.7,
    depth: 11.7,
  },
  {
    pedalName: "Grand Orbiter V3",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Phaser",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 320,
    width: 6.4,
    height: 5.7,
    depth: 12.1,
  },
  {
    pedalName: "Hizumitas",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 300,
    inspiredBy: "Triangle Big Muff",

    width: 6.4,
    height: 5.7,
    depth: 12.1,
  },
  {
    pedalName: "Hoof V2",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 270,
    inspiredBy: "Green Russian Big Muff",
    width: 6.4,
    height: 5.7,
    depth: 11.7,
  },
  {
    pedalName: "Hummingbird V4",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Tremolo",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 6.4,
    height: 5.7,
    depth: 12.1,
  },
  {
    pedalName: "Park Fuzz",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 350,
    width: 6.4,
    height: 5.7,
    depth: 11.8,
    inspiredBy: "Park Amplification Park Fuzz",
  },
  {
    pedalName: "Plumes",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 6.4,
    height: 11.8,
    depth: 5.7,
  },
  {
    pedalName: "Rainbow Machine V2",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Octaver",
    additionalCategory: ["Chorus", "Delay"],

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 450,
    width: 9.3,
    height: 5.7,
    depth: 11.8,
  },
  {
    pedalName: "Spatial Delivery V2",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Envelope Filter",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 250,
    width: 6.4,
    height: 5.7,
    depth: 12.1,
  },
  {
    pedalName: "Westwood",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 280,
  },
  {
    pedalName: "Bass IQ",
    manufacturer: "EBS",
    madeIn: "China",
    category: "Envelope Filter",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 310,
    width: 6.7,
    height: 4.8,
    depth: 11.5,
  },
  {
    pedalName: "Billy Sheehan Ultimate Signature Drive",
    manufacturer: "EBS",
    series: "Signature",
    madeIn: "China",
    category: "Overdrive",
    additionalCategory: "Boost",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 420,
    width: 8.3,
    height: 4.8,
    depth: 11.5,
  },
  {
    pedalName: "Black Haze Distortion/Overdrive",
    manufacturer: "EBS",
    series: "Blue Label",
    madeIn: "China",
    category: "Distortion",
    additionalCategory: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 310,
    width: 6.1,
    height: 4.5,
    depth: 11,
  },
  {
    pedalName: "Black Haze Distortion/Overdrive",
    manufacturer: "EBS",
    series: "Blue Label",
    madeIn: "China",
    category: "Distortion",
    additionalCategory: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 310,
    width: 6.1,
    height: 4.5,
    depth: 11,
  },
  {
    pedalName: "Drive Me Crazy Distortion/Overdrive",
    manufacturer: "EBS",
    series: "Blue Label",
    madeIn: "China",
    category: "Distortion",
    additionalCategory: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 310,
    width: 6.1,
    height: 4.5,
    depth: 11,
  },
  {
    pedalName: "DynaVerb",
    manufacturer: "EBS",
    madeIn: "Sweden",
    year: 2015,
    category: "Reverb",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: false,
    polarity: "Center Negative",
    circuit: "Digital",

    color: "Pink",
    weight: 400,
    specialFeatures: "Selection between 3 reverb types - Hall, Room, Plate",
    width: 7,
    height: 3.5,
    depth: 11.5,
  },
  {
    pedalName: "MetalDrive Studio Edition",
    manufacturer: "EBS",
    series: "Studio Edition",
    madeIn: "China",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: [9, 12],
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    specialFeatures: "MOD selector for a variety of distortion sounds",
    width: 7,
    height: 3.5,
    depth: 11.5,
  },
  {
    pedalName: "MultiComp",
    manufacturer: "EBS",
    madeIn: "Sweden",
    year: 2015,
    category: "Compressor",

    jacksMountedOn: "Sides",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 7.0,
    height: 3.5,
    depth: 11.5,
  },
  {
    pedalName: "MultiDrive Studio Edition",
    manufacturer: "EBS",
    madeIn: "China",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 6.1,
    height: 4.5,
    depth: 11,
    specialFeatures: "3 Modes: Tubesim/Flat/Standard",
  },
  {
    pedalName: "Octabass",
    manufacturer: "EBS",
    madeIn: "China",
    category: "Octaver",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 310,
    width: 6.6,
    height: 4.8,
    depth: 11.4,
  },
  {
    pedalName: "Red Twister",
    manufacturer: "EBS",
    madeIn: "Sweden",
    year: 2015,
    category: "Chorus",
    additionalCategory: "Flanger",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,
    width: 7,
    height: 3.5,
    depth: 11.5,
  },
  {
    pedalName: "The Drive",
    manufacturer: "EBS",
    series: "Blue Label",
    madeIn: "China",
    category: "Overdrive",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 300,
    width: 6.1,
    height: 4.5,
    depth: 11,
  },
  {
    pedalName: "UniChorus Studio Edition",
    manufacturer: "EBS",
    madeIn: "China",
    category: "Chorus",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 400,

    specialFeatures: "Stereo Output",
    width: 7,
    height: 3.5,
    depth: 11.5,
  },
  {
    pedalName: "Krankjorum",
    manufacturer: "Effesk",
    madeIn: "The Netherlands",
    category: "Fuzz",
    additionalCategory: "Noise Generator",

    jacksMountedOn: "One side",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 9,
    circuit: "Analog",

    weight: 350,
    specialFeatures: "Pitch Shift",
    width: 6.6,
    height: 3.5,
    depth: 12.1,
  },
  {
    pedalName: "Sonic Salvation",
    manufacturer: "Effesk",
    madeIn: "The Netherlands",
    category: "Fuzz",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 420,
    inspiredBy: "Jordan Boss Tone",
    width: 7.9,
    height: 5.3,
    depth: 12.9,
  },
  {
    pedalName: "Big Muff Op-Amp",
    manufacturer: "Electro-Harmonix",
    series: "Big Muff Compacts",
    madeIn: "USA",
    category: "Fuzz",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 640,
    inspiredBy: "EHX Big Muff V4",
    width: 7,
    height: 5.3,
    depth: 11.4,
  },
  {
    pedalName: "Big Muff Pi",
    manufacturer: "Electro-Harmonix",
    category: "Fuzz",
    additionalCategory: "Distortion",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 700,
    width: 14,
    height: 7.6,
    depth: 17.3,
  },
  {
    pedalName: "Flatiron Fuzz",
    manufacturer: "Electro-Harmonix",
    category: "Fuzz",
    additionalCategory: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 250,
    width: 7,
    height: 5.1,
    depth: 11.5,
    inspiredBy: "ProCo RAT 2",
    specialFeatures: "op-amp powered",
  },
  {
    pedalName: "Green Russian Big Muff",
    manufacturer: "Electro-Harmonix",
    category: "Fuzz",
    additionalCategory: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 250,
    width: 7,
    height: 5.1,
    depth: 11.5,
    inspiredBy: "Electro-Harmonix Sovtek Tall Font Green Russian Big Muff",
  },
  {
    pedalName: "Hot Tubes Overdrive",
    manufacturer: "Electro-Harmonix",
    category: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: false,
    voltage: 12,
    polarity: "Proprietary PSU",
    circuit: "Analog",

    weight: 500,
    width: 12,
    height: 4.7,
    depth: 18.9,
  },
  {
    pedalName: "Memory Toy",
    manufacturer: "Electro-Harmonix",
    series: "Nano series",
    category: "Delay",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 250,
    width: 7.0,
    height: 5.4,
    depth: 11.5,
    inspiredBy: "Electro-Harmonix Memory Man",
    specialFeatures: "MOD Toggle Switch",
  },
  {
    pedalName: "Mini Q-Tron",
    manufacturer: "Electro-Harmonix",
    madeIn: "USA",
    category: "Envelope Filter",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "TRS",
    circuit: "Analog",

    weight: 500,

    width: 10.2,
    height: 8.9,
    depth: 12.1,
  },
  {
    pedalName: "Nano Big Muff Pi",
    manufacturer: "Electro-Harmonix",
    category: "Fuzz",
    additionalCategory: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 250,
    inspiredBy: "Electro Harmonix Big Muff Pi",
    width: 6.2,
    height: 5,
    depth: 11,
  },
  {
    pedalName: "OD Glove",
    manufacturer: "Electro-Harmonix",
    series: "Nano series",
    madeIn: "USA",
    category: "Overdrive",
    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 300,
    inspiredBy: "Fulltone OCD",
    specialFeatures: "Mode Toggle Switch",
    width: 7.0,
    height: 5.4,
    depth: 11.5,
  },
  {
    pedalName: "Small Stone V2 (1978)",
    manufacturer: "Electro-Harmonix",
    madeIn: "USA",
    year: 1978,
    category: "Chorus",

    jacksMountedOn: "Top",
    bypass: "Buffered bypass",
    battery: true,
    voltage: 9,
    polarity: "TRS",
    circuit: "Analog",

    weight: 400,

    width: 8.5,
    height: 5.5,
    depth: 13.5,
  },
  {
    pedalName: "Soul Food",
    manufacturer: "Electro-Harmonix",
    madeIn: "USA",
    year: "2010's",
    category: "Overdrive",
    additionalCategory: "Boost",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 250,
    inspiredBy: "Klon",
    specialFeatures: "Switchable Buffer",
    width: 7,
    height: 5.4,
    depth: 11.5,
  },
  {
    pedalName: "Triangle Big Muff",
    manufacturer: "Electro-Harmonix",
    category: "Fuzz",
    additionalCategory: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 350,
    inspiredBy: "Electro-Harmonix Big Muff Pi V1",
    width: 7,
    height: 5.3,
    depth: 11.4,
  },
  {
    pedalName: "Pugilist Distortion",
    manufacturer: "Fender",
    madeIn: "China",
    category: "Distortion",

    jacksMountedOn: "Sides",
    bypass: "True bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 540,
    width: 14,
    height: 7.6,
    depth: 19,
  },
  {
    pedalName: "Plasma Pedal",
    manufacturer: "Gamechanger Audio",
    madeIn: "Latvia",
    category: "Distortion",
    additionalCategory: "Overdrive",

    jacksMountedOn: "Top",
    bypass: "True bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",

    weight: 840,
    width: 9.4,
    height: 7,
    depth: 14.8,
  },
];
