const effectPedals = [
  {
    pedalName: "Utopia Analog Delay",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Delay",
    additionalcategory: "Modulation",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 290,
    width: 6.4,
    height: 5.9,
    depth: 11.8,
  },
  {
    pedalName: "#1echo",
    manufacturer: "Electro-Harmonix",
    madeIn: "USA",
    category: "Delay",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 450,
    famousUsers: "Flea",
    width: 10.2,
    height: 8.9,
    depth: 12.1,
  },
  {
    pedalName: "3699 Fuzz",
    manufacturer: "Danelectro",
    madeIn: "China",
    category: "Fuzz",
    additionalcategory: "Octaver",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weight: 270,
    basedOnFamousModel: "FOXX Tone Machine",
    width: 5.8,
    height: 5.8,
    depth: 11.5,
  },
  {
    name: "Back Talk",
    manufacturer: "Danelectro",
    madeIn: "China",
    category: "Delay",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 250, // weight in grams
    specialFeatures: "Reverse Delay",
    width: 5.8, // width in cm
    height: 5.8, // height in cm
    depth: 11.5, // depth in cm
  },

  {
    pedalName: "385 Overdrive",
    manufacturer: "Walrus Audio",
    madeIn: "USA",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 270,
    basedOnFamousModel: "385 Bell & Howell Projector",
    width: 6.6,
    height: 5.8,
    depth: 12.1,
  },
  {
    pedalName: "DRV No3",
    manufacturer: "1981 Inventions",
    madeIn: "USA",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 400,
    basedOnFamousModel: "ProCo RAT",
    width: 8.6,
    height: 4.6,
    depth: 10.7,
  },
  {
    pedalName: "Cinnamon Drive",
    manufacturer: "Aclam",
    madeIn: "Spain",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 410,
    width: 13.6,
    height: 5.5,
    depth: 8.7,
  },
  {
    pedalName: "Dr. Robert",
    manufacturer: "Aclam",
    madeIn: "Spain",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 410,
    basedOnFamousModel: "Vox UL730",
    specialFeatures: "Bass and Guitar Pedal",
    width: 13.6,
    height: 5.5,
    depth: 8.7,
  },
  {
    pedalName: "The Woman Tone",
    manufacturer: "Aclam",
    madeIn: "Spain",
    year: "2020's",
    category: "Overdrive",
    additionalcategory: "Boost",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    colour: "Purple",
    weight: 420,
    specialFeatures: "Pickup Simulator",
    width: 13.7,
    height: 5.5,
    depth: 8.8,
  },
  {
    pedalName: "The Windmiller",
    manufacturer: "Aclam",
    madeIn: "Spain",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 450,
    basedOnFamousModel: "Grampian 636 Spring Reverb Pre Amp",
    famousUsers: "Pete Townsend",
    width: 13.6,
    height: 5.5,
    depth: 8.7,
  },
  {
    pedalName: "The Windmiller",
    manufacturer: "Aclam",
    madeIn: "Spain",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 450,
    basedOnFamousModel: "Grampian 636 Spring Reverb Pre Amp",
    famousUsers: "Pete Townsend",
    width: 13.6,
    height: 5.5,
    depth: 8.7,
  },
  {
    pedalName: "Agro",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 480,
    famousUsers:
      "Mikey Way, Justin Meldal Johnsen, Alex Dean, Dick Lövgren, Paulo Jr., Chris Chaney, Tomasz Wróblewski, Rhonda Smith",
    width: 6.8,
    height: 5.3,
    depth: 11.3,
  },
  {
    pedalName: "Chorusaurus",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Chorus",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 480,
    width: 6.8,
    height: 5.3,
    depth: 13.3,
    famousUsers: "Paulo Jr., Dallon Weekes",
  },

  {
    pedalName: "Filter Twin",
    manufacturer: "Aguilar",
    madeIn: "USA",
    year: "2000s",
    category: "Envelope Filter",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    colour: "Green",
    weight: 490,
    width: 6.8,
    height: 13.3,
    depth: 5.3,
  },

  {
    pedalName: "Fuzzistor",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 480,
    width: 6.8,
    height: 5.3,
    depth: 13.3,
  },

  {
    pedalName: "Grape Phaser",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Phaser",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 290,
    famousUsers: "Paul Turner",
    width: 6.8,
    height: 5.3,
    depth: 13.3,
  },

  {
    pedalName: "Octamizer",
    manufacturer: "Aguilar",
    madeIn: "USA",
    year: "2000s",
    category: "Octaver",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    colour: "Red",
    weight: 490,
    width: 6.8,
    height: 13.3,
    depth: 5.3,
  },

  {
    pedalName: "TLC Compressor",
    manufacturer: "Aguilar",
    madeIn: "USA",
    year: "2000s",
    category: "Compressor",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    colour: "Blue",
    weight: 490,
    width: 6.8,
    height: 13.3,
    depth: 5.3,
  },
  {
    pedalName: "The Windmiller",
    manufacturer: "Aclam",
    madeIn: "Spain",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 450,
    basedOnFamousModel: "Grampian 636 Spring Reverb Pre Amp",
    famousUsers: "Pete Townsend",
    width: 13.6,
    height: 5.5,
    depth: 8.7,
  },

  {
    pedalName: "Agro",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 480,
    famousUsers:
      "Mikey Way, Justin Meldal Johnsen, Alex Dean, Dick Lövgren, Paulo Jr., Chris Chaney, Tomasz Wróblewski, Rhonda Smith",
    width: 6.8,
    height: 5.3,
    depth: 11.3,
  },

  {
    pedalName: "Chorusaurus",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Chorus",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 480,
    width: 6.8,
    height: 5.3,
    depth: 13.3,
    famousUsers: "Paulo Jr., Dallon Weekes",
  },

  {
    pedalName: "Filter Twin",
    manufacturer: "Aguilar",
    madeIn: "USA",
    year: "2000s",
    category: "Envelope Filter",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    colour: "Green",
    weight: 490,
    width: 6.8,
    height: 13.3,
    depth: 5.3,
  },

  {
    pedalName: "Fuzzistor",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 480,
    width: 6.8,
    height: 5.3,
    depth: 13.3,
  },

  {
    pedalName: "Grape Phaser",
    manufacturer: "Aguilar",
    madeIn: "USA",
    category: "Phaser",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 290,
    famousUsers: "Paul Turner",
    width: 6.8,
    height: 5.3,
    depth: 13.3,
  },

  {
    pedalName: "Octamizer",
    manufacturer: "Aguilar",
    madeIn: "USA",
    year: "2000s",
    category: "Octaver",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    colour: "Red",
    weight: 490,
    width: 6.8,
    height: 13.3,
    depth: 5.3,
  },

  {
    pedalName: "TLC Compressor",
    manufacturer: "Aguilar",
    madeIn: "USA",
    year: "2000s",
    category: "Compressor",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    colour: "Blue",
    weight: 490,
    width: 6.8,
    height: 13.3,
    depth: 5.3,
  },

  {
    pedalName: "Alien Comp",
    manufacturer: "Analog Alien",
    madeIn: "USA",
    category: "Compressor",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 400,
    width: 10,
    height: 5.8,
    depth: 12.2,
  },

  {
    pedalName: "Alien Twister",
    manufacturer: "Analog Alien",
    madeIn: "USA",
    category: "Buffer, Fuzz",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass, True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 400,
    width: 10.9,
    height: 6.1,
    depth: 5.3,
  },

  {
    pedalName: "Bucket Seat",
    manufacturer: "Analog Alien",
    madeIn: "USA",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 400,
    width: 10,
    height: 5.8,
    depth: 12.2,
  },

  {
    pedalName: "Fuzz Bubble 45",
    manufacturer: "Analog Alien",
    madeIn: "USA",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 500,
    width: 12.6,
    height: 9.5,
    depth: 5.5,
  },

  {
    pedalName: "Joe Walsh Double Classic",
    manufacturer: "Analog Alien",
    madeIn: "USA",
    category: "Compressor, Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 800,
    famousUsers: "Joe Walsh",
    width: 14.6,
    height: 3.8,
    depth: 12,
  },

  {
    pedalName: "Power Pack",
    manufacturer: "Analog Alien",
    madeIn: "USA",
    category: "Boost",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 400,
    width: 6.6,
    height: 3.5,
    depth: 12.1,
  },

  {
    pedalName: "Rumble Seat",
    manufacturer: "Analog Alien",
    madeIn: "USA",
    category: "Delay, Overdrive, Reverb",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 800,
    width: 14.6,
    height: 3.8,
    depth: 12,
  },
  {
    pedalName: "Ages",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Tremolo",
    additionalcategory: "Harmonic Tremolo",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 500,
    specialFeatures: "Spinner Expression Pedal",
    width: 12,
    height: 8,
    depth: 16,
  },

  {
    pedalName: "Bitoun Fuzz",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 280,
    specialFeatures: "Dip Switches",
    width: 6.6,
    height: 5.9,
    depth: 12,
  },

  {
    pedalName: "Bitoun Fuzz",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 280,
    specialFeatures: "Dip Switches",
    width: 6.6,
    height: 5.9,
    depth: 12,
  },

  {
    pedalName: "Element",
    manufacturer: "Anasounds",
    series: "Elements",
    madeIn: "France",
    category: "Reverb",
    additionalcategory: "Drive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 290,
    basedOnFamousModel: "Fender Twin Reverb",
    specialFeatures: "Switchable reverb tanks",
    width: 6.4,
    height: 5.9,
    depth: 11.8,
  },

  {
    pedalName: "High Voltage",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 290,
    specialFeatures: "Bass Cut",
    width: 12,
    height: 8,
    depth: 16,
  },

  {
    pedalName: "Savage",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 430,
    width: 6,
    height: 4,
    depth: 12,
  },

  {
    pedalName: "Tremolo",
    manufacturer: "Anasounds",
    madeIn: "France",
    category: "Tremolo",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 500,
    specialFeatures: "Spinner Expression Pedal",
    width: 12,
    height: 8,
    depth: 16,
  },

  {
    pedalName: "PRO FF Sub Harmonic Generator",
    manufacturer: "Ashdown",
    series: "Pro category",
    madeIn: "China",
    category: "Octaver",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 600,
    width: 7.3,
    height: 4.5,
    depth: 11.6,
  },

  {
    pedalName: "PRO category Double Shot",
    manufacturer: "Ashdown",
    series: "Pro category",
    madeIn: "China",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 600,
    width: 7.3,
    height: 4.5,
    depth: 11.6,
  },
  {
    pedalName: "Fatbee Overdrive",
    manufacturer: "Beetronics",
    series: "Babee",
    madeIn: "USA",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.23,
    width: 5.7,
    height: 3.5,
    depth: 11.4,
  },

  {
    pedalName: "Vezzpa",
    manufacturer: "Beetronics",
    madeIn: "USA",
    category: "Fuzz",
    additionalcategory: "Octaver",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.32,
    width: 6.3,
    height: 5.7,
    depth: 11.4,
  },

  {
    pedalName: "HT-Drive",
    manufacturer: "Blackstar Amplification",
    series: "HT Pedals",
    madeIn: "China",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "Yes",
    colour: "Silver",
    weight: 1.2,
    width: 16,
    height: 8,
    depth: 12,
  },
  {
    pedalName: "HM300 Heavy Metal",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.3,
    basedOnFamousModel: "BOSS HM-2",
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },
  {
    pedalName: "OD300 Overdrive Distortion",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Overdrive",
    additionalcategory: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.3,
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },
  {
    pedalName: "SF300 Super Fuzz",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.3,
    basedOnFamousModel: "BOSS FZ-2",
    specialFeatures: "Secret Mode",
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },
  {
    pedalName: "TM300 Tube Amp Modeler",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Amp Modeler",
    type: "Pedal",
    jacksMountedOn: "Sides",
    colour: "Blue",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.3,
    basedOnFamousModel: "Tech 21 GT2",
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },
  {
    pedalName: "TO800 Vintage Tube Overdrive",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.3,
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },

  {
    pedalName: "UC200 Ultra Chorus",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Chorus",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.3,
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },

  {
    pedalName: "UM300 Ultra Metal",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.3,
    basedOnFamousModel: "BOSS MT-2",
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },
  {
    pedalName: "UV300 Ultra Vibrato",
    manufacturer: "Behringer",
    series: "Compact",
    madeIn: "China",
    category: "Vibrato",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.3,
    width: 8.6,
    height: 6.1,
    depth: 15.6,
  },

  {
    pedalName: "AC-3 Acoustic Simulator",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Acoustic Simulator",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.44,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "AW-3 Dynamic Wah",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Wah",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.42,
    specialFeatures: "Talking Wah effect",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "BB-1X Bass Driver",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.45,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "BC-1X Bass Comp",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Compressor",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.45,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "BD-2 Blues Driver",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.36,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "BD-2W Blues Driver",
    manufacturer: "BOSS",
    series: "WAZA CRAFT",
    madeIn: "Taiwan",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.43,
    basedOnFamousModel: "BOSS BD-2",
    famousUsers: "Jim James, Syu",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "BF-3 Flanger",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Flanger",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.42,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "CE-2 Chorus Ensemble",
    manufacturer: "BOSS",
    madeIn: "Japan",
    year: "1977",
    category: "Chorus",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.45,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "Another BOSS Pedal",
    manufacturer: "BOSS",
    // More data for the next BOSS pedal...
  },
  {
    pedalName: "CE-2W Chorus",
    manufacturer: "BOSS",
    series: "Waza Craft Series",
    madeIn: "Taiwan",
    category: "Chorus",
    additionalcategory: "Vibrato",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.45,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "CE-5 Chorus Ensemble",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Chorus",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.41,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "CEB-3 Bass Chorus",
    manufacturer: "BOSS",
    series: "Compact Series",
    madeIn: "Taiwan",
    category: "Chorus",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.45,
    famousUsers: ["Jason Newsted", "Simon Gallup"],
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "CH-1 Super Chorus",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Chorus",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.4,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "CP-1X Compressor",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Compressor",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.45,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "CS-3 Compression Sustainer",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Compressor",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.4,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "DC-2W Dimension C",
    manufacturer: "BOSS",
    series: "Waza Craft Series",
    madeIn: "Taiwan",
    category: "Chorus",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.45,
    basedOnFamousModel: "BOSS DC-2, Roland SDD-320",
    specialFeatures: "Stereo Input & Output",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "DD-3 Digital Delay",
    manufacturer: "BOSS",
    series: "Digital Delay Series",
    madeIn: "Taiwan",
    year: "1986-2019",
    category: "Delay",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.46,
    famousUsers: [
      "Dave Grohl",
      "Slash",
      "Matthew Bellamy",
      "Tom Morello",
      "Dan Auerbach",
      "Thom Yorke",
      "Joe Satriani",
      "Joe Bonamassa",
      "Adam Jones",
      "Josh Klinghoffer",
      "Prince",
    ],
    specialFeatures: "Hold function",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "DD-3T Digital Delay",
    manufacturer: "BOSS",
    series: "Compact",
    madeIn: "Malaysia",
    category: "Delay",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.42,
    basedOnFamousModel: "DD-3",
    famousUsers: "Yngwie Malmsteen",
    specialFeatures: "Tap Tempo",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "DD-7 Digital Delay",
    manufacturer: "BOSS",
    series: "Digital Delay Series",
    madeIn: "Taiwan",
    category: "Delay",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.44,
    specialFeatures: "Hold Function",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "DD-8 Digital Delay",
    manufacturer: "BOSS",
    series: "Compact",
    madeIn: "Malaysia",
    category: "Delay",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.44,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "DM-2 Delay",
    manufacturer: "BOSS",
    series: "Compact",
    madeIn: "Japan",
    category: "Delay",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.46,
    famousUsers:
      "Dave Grohl, John Frusciante, Kurt Cobain, Joe Satriani, Cliff Burton, Prince, Mike McCready, Gary Moore, Beck, John 5",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DM-2W Delay",
    manufacturer: "BOSS",
    series: "Waza Craft Series",
    madeIn: "Taiwan",
    category: "Delay",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.46,
    basedOnFamousModel: "BOSS DM-2",
    famousUsers: "Steve Vai, John 5",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DS-1 (Vintage)",
    manufacturer: "BOSS",
    madeIn: "Japan",
    series: "Compact",
    year: "1979",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    color: "Black",
    weight: 0.4,
    famousUsers: [
      "John Frusciante",
      "Kurt Cobain",
      "Steve Vai",
      "Joe Satriani",
      "Billie Joe Armstrong",
    ],
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DS-1 Distortion",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.4,
    famousUsers: [
      "Steve Vai",
      "Joe Satriani",
      "Kurt Cobain",
      "Mike Stern",
      "Steve Rothery",
      "Glenn Frey",
      "Doug Aldrich",
      "Josh Klinghoffer",
    ],
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DS-1W",
    manufacturer: "BOSS",
    madeIn: "Japan",
    manufacturerPartNumber: "DS-1W",
    serialNumber: "114703",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    color: "Orange",
    weight: 0.4,
    basedOnFamousModel: "DS-1",
    width: 6.4,
    height: 5.1,
    depth: 11.9,
  },
  {
    pedalName: "DS-1X Distortion",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.45,
    specialFeatures: "MDP",
    width: 7.2,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "DS-2 Turbo Distortion",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.4,
    basedOnFamousModel: "DS-1",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "FZ-1w",
    manufacturer: "BOSS",
    madeIn: "Japan",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    color: "Grey",
    weight: 0.44,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "FZ-5 Fuzz",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.44,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "HM-2",
    manufacturer: "BOSS",
    madeIn: "Japan",
    series: "Compact",
    year: "1990s",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "No",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    color: "Black",
    weight: 0.4,
    famousUsers: ["Entombed"],
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "HM-2W",
    manufacturer: "BOSS",
    madeIn: "Japan",
    series: "Waza Craft",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.44,
    basedOnFamousModel: "HM-2",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "JB-2 Angry Driver",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",
    additionalcategory: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.44,
    basedOnFamousModel: "BOSS BD-2, JHS Angry Charlie",
    specialFeatures: "Order swapping - Remote Switching",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "MD-2 Mega Distortion",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.41,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "ML-2 Metal Core",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.44,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "MO-2 Multi Overtone",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overtone Generator",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.43,
    width: 7,
    height: 5.5,
    depth: 12.5,
  },

  {
    pedalName: "MT-2 Metal Zone",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.41,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "MT-2W Metal Zone",
    manufacturer: "BOSS",
    series: "WAZA CRAFT",
    madeIn: "Japan",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.41,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "OC-3 Super Octave",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Octaver",
    additionalcategory: "Poly Octave/OC-2 Mode",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.44,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "OC-5",
    manufacturer: "BOSS",
    series: "Compact",
    madeIn: "Taiwan",
    category: "Octaver",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    weight: 0.44,
    basedOnFamousModel: "BOSS OC-2",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "OD-1 (1984)",
    manufacturer: "BOSS",
    series: "Compact",
    madeIn: "Japan",
    year: 1984,
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.4,
    famousUsers: [
      "Tony Iommi",
      "Joe Satriani",
      "Pete Townshend",
      "Ed O'Brien",
      "Rory Gallagher",
      "Jerry Garcia",
      "Richie Sambora",
      "Lindsey Buckingham",
    ],
    width: 7.9,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "OD-1X Overdrive",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.45,
    famousUsers: ["Orianthi", "Brandon Small", "Chris Payton"],
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "OD-3 OverDrive",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.41,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "OD-1X Overdrive",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.45,
    famousUsers: ["Orianthi", "Brandon Small", "Chris Payton"],
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "ODB-3 Bass OverDrive",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    color: "Yellow",
    weight: 0.42,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "OS-2 Overdrive/Distortion",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Overdrive",
    additionalcategory: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.4,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "PH-1 Phaser (1979)",
    manufacturer: "BOSS",
    madeIn: "Japan",
    year: 1979,
    category: "Phaser",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.4,
    famousUsers: ["Jake E. Lee"],
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },

  {
    pedalName: "PH-3 Phase Shifter",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Phaser",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.42,
    basedOnFamousModel: "BOSS PH-1",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "PS-6 Harmonist",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Pitch Shifter",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.44,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "RE-2",
    manufacturer: "BOSS",
    series: "Compact",
    madeIn: "Malaysia",
    year: 2022,
    category: "Delay",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 4.5,
    basedOnFamousModel: "RE:201 Space Echo",
    specialFeatures: "Carry Over Switch",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "RE-20 Space Echo",
    manufacturer: "BOSS",
    series: "20",
    madeIn: "Taiwan",
    category: "Delay",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 1.1,
    basedOnFamousModel: "RE:201 Space Echo",
    width: 17.3,
    height: 5.7,
    depth: 15.8,
  },

  {
    pedalName: "SY-1",
    manufacturer: "BOSS",
    madeIn: "Malaysia",
    category: "Synthesizer",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.45,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "RV-6 Reverb",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Reverb",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.45,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "SD-1 Super Overdrive",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.4,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "SD-1W Super Overdrive",
    manufacturer: "BOSS",
    series: "WAZA CRAFT",
    madeIn: "Taiwan",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.43,
    basedOnFamousModel: "BOSS SD-1",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "SL-2 Slicer",
    manufacturer: "BOSS",
    madeIn: "Japan",
    year: "2020's",
    category: "Beat Generator",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    colour: "Green",
    weight: 0.4,
    basedOnFamousModel: "BOSS SL-20",
    width: 6.4,
    height: 5.1,
    depth: 11.9,
  },
  {
    pedalName: "ST-2 Power Stack",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Distortion",
    additionalcategory: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.44,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "TB-2W",
    manufacturer: "BOSS",
    madeIn: "Japan",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: "7, 9, 12",
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.44,
    basedOnFamousModel: "ToneBender",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "TE-2 Tera Echo",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Delay",
    additionalcategory: "Ambient",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.43,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "TR-2 Tremolo",
    manufacturer: "BOSS",
    madeIn: "Taiwan",
    category: "Tremolo",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: "No",
    weight: 0.4,
    famousUsers:
      "Eric Clapton, Billie Joe Armstrong, Tom Morello, Dan Auerbach, Noel Gallagher, Jonny Buckland",
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "VB-2W Vibrato",
    manufacturer: "BOSS",
    series: "Waza Craft Series",
    madeIn: "Taiwan",
    category: "Vibrato",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: "Yes",
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: "No",
    weight: 0.45,
    width: 7.3,
    height: 5.9,
    depth: 12.9,
  },
  {
    pedalName: "Classic Chorus",
    manufacturer: "Carl Martin",
    series: "Vintage Series",
    madeIn: "China",
    category: "Chorus",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weightInKg: 0.35,
    widthInCm: 9.5,
    heightInCm: 5.6,
    depthInCm: 12,
  },
  {
    pedalName: "Classic Flanger",
    manufacturer: "Carl Martin",
    series: "Vintage Series",
    madeIn: "China",
    category: "Flanger",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Hybrid",
    tubeEquipped: false,
    weightInKg: 0.35,
    widthInCm: 9.5,
    heightInCm: 5.6,
    depthInCm: 12,
  },
  {
    pedalName: "Classic Opto Compressor",
    manufacturer: "Carl Martin",
    series: "Vintage Series",
    madeIn: "China",
    category: "Compressor",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    color: "Blue",
    weightInKg: 0.35,
    widthInCm: 9.5,
    heightInCm: 5.6,
    depthInCm: 12,
  },
  {
    name: "DC Drive",
    manufacturer: "Carl Martin",
    series: "Vintage Series",
    madeIn: "China",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weightInKg: 0.35,
    specialFeatures: "Reg-Fat switch for gain variety",
    widthInCm: 6,
    heightInCm: 5,
    depthInCm: 11.5,
  },
  {
    name: "Headroom",
    manufacturer: "Carl Martin",
    series: "Vintage Series",
    madeIn: "Denmark",
    category: "Reverb",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weightInKg: 1.2,
    famousUsers: "Johnny Marr",
    widthInCm: 26,
    heightInCm: 7.1,
    depthInCm: 15,
  },
  {
    pedalName: "Ottawa",
    manufacturer: "Carl Martin",
    series: "Vintage Series",
    madeIn: "China",
    category: "Auto Wah",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    weightInKg: 0.34,
    widthInCm: 6,
    heightInCm: 5,
    depthInCm: 11.5,
  },
  {
    pedalName: "Panama",
    manufacturer: "Carl Martin",
    series: "Vintage Series",
    madeIn: "China",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weightInKg: 0.34,
    widthInCm: 6,
    heightInCm: 5,
    depthInCm: 11.5,
  },
  {
    pedalName: "PlexiRanger",
    manufacturer: "Carl Martin",
    madeIn: "China",
    category: "Overdrive",
    additionalcategory: "Treble Booster",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weightInKg: 0.4,
    basedOnFamousModel: "Range Master",
    famousUsers: "Brett Kingman",
    widthInCm: 10,
    heightInCm: 5.8,
    depthInCm: 12.2,
  },
  {
    name: "PlexiTone Lo Gain",
    manufacturer: "Carl Martin",
    series: "Pro Series",
    madeIn: "China",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: false,
    voltage: 9,
    circuit: "Analog",
    tubeEquipped: false,
    weightInKg: 0.28,
    basedOnFamousModel: "Carl Martin PlexiTone",
    famousUsers: "Pete Thorn, James Mulvaney",
    widthInCm: 7.2,
    heightInCm: 5.7,
    depthInCm: 11.2,
  },
  {
    pedalName: "Purple Moon",
    manufacturer: "Carl Martin",
    series: "Vintage Series",
    madeIn: "China",
    category: "Vibe",
    additionalcategory: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weightInKg: 0.35,
    famousUsers: "Brian Ray, Michael Thompson, James Mulvaney, Alberto Barrero",
    specialFeatures: "Optional Fuzz added to the circuit",
    widthInCm: 6,
    heightInCm: 5,
    depthInCm: 11.5,
  },
  {
    name: "Red Repeat",
    manufacturer: "Carl Martin",
    series: "Vintage Series",
    madeIn: "Denmark",
    category: "Delay",
    additionalcategory: "Acoustic Simulator",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Hybrid",
    tubeEquipped: false,
    weightInKg: 0.35,
    widthInCm: 9.5,
    heightInCm: 5.6,
    depthInCm: 12,
  },
  {
    pedalName: "single Channel AC Tone",
    manufacturer: "Carl Martin",
    series: "Pro-Series",
    madeIn: "China",
    year: "2010s",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weightInKg: 0.28,
    basedOnFamousModel: "Carl Martin AC Tone",
    famousUsers: ["Pete Thorn", "Joash Gooch", "Johnny Marr", "Rick Graham"],
    specialFeatures: "Active Buffered Bypass",
    widthInCm: 7.2,
    heightInCm: 5.7,
    depthInCm: 11.2,
  },
  {
    pedalName: "Surf Trem",
    manufacturer: "Carl Martin",
    series: "Vintage Series",
    madeIn: "China",
    category: "Tremolo",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weightInKg: 0.35,
    widthInCm: 6,
    heightInCm: 5,
    depthInCm: 11.5,
  },
  {
    name: "Tube Driver (1988)",
    manufacturer: "Chandler Industries",
    madeIn: "USA",
    serialNumber: "207947",
    year: 1988,
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: false,
    voltage: 12,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: true,
    colour: "Cream",
    weight: 1000, // weight in grams
    basedOnFamousModel: "B.K Butler Tube Driver",
    famousUsers: "David Gilmour, Billy Gibbons, Eric Johnson, Joe Satriani",
    width: 10.5, // width in cm
    height: 9, // height in cm
    depth: 17.1, // depth in cm
  },
  {
    name: "Supa Tonebender (1974)",
    manufacturer: "Colorsound",
    madeIn: "UK",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 650, // weight in grams
    basedOnFamousModel: "Electro Harmonix Ram's Head Big Muff",
    famousUsers: "Steve Hackett",
    width: 12, // width in cm
    height: 4.2, // height in cm
    depth: 22, // depth in cm
  },
  {
    name: "Alpha Omicron",
    manufacturer: "Darkglass Electronics",
    madeIn: "Finland",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 250, // weight in grams
    basedOnFamousModel: "Darkglass Alpha · Omega",
    width: 7.5, // width in cm
    height: 4.5, // height in cm
    depth: 11.3, // depth in cm
  },
  {
    name: "Microtubes B3K V2",
    manufacturer: "Darkglass Electronics",
    madeIn: "Finland",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 290, // weight in grams
    width: 7.5, // width in cm
    height: 4.5, // height in cm
    depth: 11.3, // depth in cm
  },
  {
    name: "Vintage Microtubes",
    manufacturer: "Darkglass Electronics",
    madeIn: "Finland",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 250, // weight in grams
    width: 7.5, // width in cm
    height: 4.5, // height in cm
    depth: 11.3, // depth in cm
  },
  {
    name: "Fuzz War",
    manufacturer: "Death By Audio",
    madeIn: "USA",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 540, // weight in grams
    width: 11.8, // width in cm
    height: 6.2, // height in cm
    depth: 14.4, // depth in cm
  },
  {
    name: "Germanium Filter",
    manufacturer: "Death By Audio",
    madeIn: "USA",
    manufacturerPartNumber: "DBA GERMANIUM",
    year: "2020's",
    category: "Filter",
    additionalcategory: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    colour: "Gold",
    weight: 300, // weight in grams
    width: 6.4, // width in cm
    height: 5.7, // height in cm
    depth: 12.7, // depth in cm
  },
  {
    name: "CPR1 Compressor",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Compressor",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 400, // weight in grams
    specialFeatures: "EQ control for overall frequency balance shifting",
    width: 9.8, // width in cm
    height: 5.4, // height in cm
    depth: 11.9, // depth in cm
  },
  {
    name: "F-Octave",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 400, // weight in grams
    basedOnFamousModel: "Foxx Tone Machine",
    width: 6.5, // width in cm
    height: 5.1, // height in cm
    depth: 12, // depth in cm
  },
  {
    name: "FBR2 Fireburst",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Fuzz",
    additionalcategory: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 350, // weight in grams
    width: 6.5, // width in cm
    height: 5.1, // height in cm
    depth: 12, // depth in cm
  },
  {
    name: "HCH1 Halo Chorus",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Chorus",
    additionalcategory: "Delay/Pitch",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Positive",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 450, // weight in grams
    width: 12, // width in cm
    height: 5.4, // height in cm
    depth: 12, // depth in cm
    specialFeatures:
      "Autoconfigurable I/O for mono, mono in/stereo out, and stereo in/stereo out operation.",
  },
  {
    name: "JDR3 J-Drive Mk3",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Overdrive",
    additionalcategory: "Boost",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 400, // weight in grams
    width: 11.9, // width in cm
    height: 5.1, // height in cm
    depth: 9.3, // depth in cm
  },
  {
    name: "MLNJr Memory Lane Jr",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Delay",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Hybrid",
    tubeEquipped: false,
    weight: 420, // weight in grams
    width: 11.9, // width in cm
    height: 5.1, // height in cm
    depth: 9.3, // depth in cm
    specialFeatures: "Tap tempo",
  },
  {
    name: "Nine Zero Two",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    year: "2010s",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 350, // weight in grams
    width: 6.4, // width in cm
    height: 6.1, // height in cm
    depth: 12.3, // depth in cm
  },
  {
    name: "TRM1 Tremolo",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Tremolo",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 450, // weight in grams
    specialFeatures:
      "Tap tempo and footswitchable double speed mode, User selectable waveforms (sharkfin, sinewave, square wave and chop)",
    width: 11.9, // width in cm
    height: 5.1, // height in cm
    depth: 9.3, // depth in cm
  },
  {
    name: "VIB1 Vibrato",
    manufacturer: "Diamond Pedals",
    madeIn: "Canada",
    category: "Vibrato",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Positive",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 480, // weight in grams
    width: 12, // width in cm
    height: 5.4, // height in cm
    depth: 12, // depth in cm
  },
  {
    name: "Carcosa Fuzz",
    series: "Compact",
    manufacturer: "DOD",
    madeIn: "China",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 450, // weight in grams
    width: 6.7, // width in cm
    height: 5.7, // height in cm
    depth: 11.9, // depth in cm
  },
  {
    name: "Overdrive Preamp 250",
    year: 1979,
    manufacturer: "DOD",
    madeIn: "USA",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 280, // weight in grams
    famousUsers: ["Yngwie Malmsteen"],
    width: 6.6, // width in cm
    height: 5.7, // height in cm
    depth: 11.8, // depth in cm
  },
  {
    name: "Vibe Machine",
    manufacturer: "Drybell",
    madeIn: "Croatia",
    category: "Vibe",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 280, // weight in grams
    famousUsers: ["Steve Stevens", "Andy Susemihl"],
    width: 6, // width in cm
    height: 3.1, // height in cm
    depth: 11.2, // depth in cm
  },
  {
    name: "Band of Gypsys Fuzz Face Mini Distortion",
    manufacturer: "Dunlop Electronics",
    series: "Authentic Hendrix",
    madeIn: "USA",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 230, // weight in grams
    basedOnFamousModel: "Tycobrahe Octavia",
    width: 8.9, // width in cm
    height: 5, // height in cm
    depth: 8.9, // depth in cm
  },
  {
    name: "Germanium Fuzz Face Mini Distortion",
    manufacturer: "Dunlop Electronics",
    madeIn: "USA",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 200, // weight in grams
    width: 8.9, // width in cm
    height: 5, // height in cm
    depth: 8.9, // depth in cm
  },
  {
    name: "Jimi Hendrix Fuzz Face Distortion",
    manufacturer: "Dunlop Electronics",
    series: "Authentic Hendrix",
    madeIn: "USA",
    category: "Fuzz",
    additionalcategory: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 350, // weight in grams
    width: 6, // width in cm
    height: 5, // height in cm
    depth: 11, // depth in cm
    basedOnFamousModel: "Dallas Arbiter Fuzz Face",
  },
  {
    name: "Jimi Hendrix Fuzz Face Mini Distortion",
    manufacturer: "Dunlop Electronics",
    series: "Authentic Hendrix",
    madeIn: "USA",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 230, // weight in grams
    width: 8.9, // width in cm
    height: 5, // height in cm
    depth: 8.9, // depth in cm
    basedOnFamousModel: "Dunlop Electronics JHF-1",
  },
  {
    name: "Silicon Fuzz Face Mini Distortion",
    manufacturer: "Dunlop Electronics",
    madeIn: "USA",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 200, // weight in grams
    width: 8.9, // width in cm
    height: 5, // height in cm
    depth: 8.9, // depth in cm
    basedOnFamousModel: "Fuzz Face",
  },
  {
    name: "Brute Drive",
    manufacturer: "E.W.S",
    madeIn: "Japan",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 240, // weight in grams
    famousUsers: "Eric Gales",
    specialFeatures: "Boost Switch",
    width: 11.2, // width in cm
    height: 5, // height in cm
    depth: 6.5, // depth in cm
  },
  {
    name: "Acapulco Gold",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 2400, // in g
    basedOnFamousModel: "Sunn Model T",
    width: 6.3, // in cm
    height: 5.7, // in cm
    depth: 11.7, // in cm
  },
  {
    name: "Afterneath V3",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Reverb",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: false,
    weight: 400, // in g
    width: 6.4, // in cm
    height: 5.7, // in cm
    depth: 12.1, // in cm
  },
  {
    name: "Bellows",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    year: "2018-2021",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    color: ["Black", "Orange"],
    weight: 250, // in g
    width: 6.4, // in cm
    height: 5.7, // in cm
    depth: 11.7, // in cm
    famousUsers: ["Matt Pike"],
  },
  {
    name: "Bit Commander V2",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Synth",
    additionalcategory: "Octaver",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 400, // in grams
    width: 6.4, // in cm
    height: 5.7, // in cm
    depth: 11.7, // in cm
  },
  {
    name: "Dispatch Master",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Delay",
    additionalcategory: "Reverb",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: false,
    weight: 250, // in grams
    width: 6.4, // in cm
    height: 5.7, // in cm
    depth: 11.7, // in cm
  },
  {
    name: "Erupter",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 260, // in grams
    width: 6.4, // in cm
    height: 5.7, // in cm
    depth: 11.7, // in cm
  },
  {
    name: "Ghost Echo V3",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Reverb",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: false,
    weight: 270, // in grams
    width: 6.4, // in cm
    height: 5.7, // in cm
    depth: 11.7, // in cm
  },
  {
    name: "Grand Orbiter V3",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Phaser",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 320, // in grams
    width: 6.4, // in cm
    height: 5.7, // in cm
    depth: 12.1, // in cm
  },
  {
    name: "Hizumitas",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 300, // in grams
    basedOnFamousModel: "Triangle Big Muff",
    famousUsers: "Wata",
    width: 6.4, // in cm
    height: 5.7, // in cm
    depth: 12.1, // in cm
  },
  {
    name: "Hoof V2",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 270, // in grams
    basedOnFamousModel: "Green Russian Big Muff",
    width: 6.4, // in cm
    height: 5.7, // in cm
    depth: 11.7, // in cm
  },
  {
    name: "Hummingbird V4",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Tremolo",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 400, // in grams
    width: 6.4, // in cm
    height: 5.7, // in cm
    depth: 12.1, // in cm
  },
  {
    name: "Park Fuzz",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 350, // in grams
    width: 6.4, // in cm
    height: 5.7, // in cm
    depth: 11.8, // in cm
    basedOnFamousModel: "Park Amplification Park Fuzz",
  },
  {
    name: "Plumes",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 400, // in grams
    width: 6.4, // in cm
    height: 11.8, // in cm
    depth: 5.7, // in cm
  },
  {
    name: "Rainbow Machine V2",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Octaver",
    additionalcategory: ["Chorus", "Delay"],
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 450, // in grams
    width: 9.3, // in cm
    height: 5.7, // in cm
    depth: 11.8, // in cm
  },
  {
    name: "Spatial Delivery V2",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Envelope Filter",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 250, // in grams
    width: 6.4, // in cm
    height: 5.7, // in cm
    depth: 12.1, // in cm
  },
  {
    name: "Westwood",
    manufacturer: "Earthquaker Devices",
    madeIn: "USA",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 280, // in grams
  },
  {
    name: "Bass IQ",
    manufacturer: "EBS",
    madeIn: "China",
    category: "Envelope Filter",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 310, // in grams
    width: 6.7, // in cm
    height: 4.8, // in cm
    depth: 11.5, // in cm
  },
  {
    name: "Billy Sheehan Ultimate Signature Drive",
    manufacturer: "EBS",
    series: "Signature",
    madeIn: "China",
    category: "Overdrive",
    additionalcategory: "Boost",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 420, // in grams
    width: 8.3, // in cm
    height: 4.8, // in cm
    depth: 11.5, // in cm
    famousUsers: ["Billy Sheehan"],
  },
  {
    name: "Black Haze Distortion/Overdrive",
    manufacturer: "EBS",
    series: "Blue Label",
    madeIn: "China",
    category: "Distortion",
    additionalcategory: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 310, // in grams
    width: 6.1, // in cm
    height: 4.5, // in cm
    depth: 11, // in cm
  },
  {
    name: "Black Haze Distortion/Overdrive",
    manufacturer: "EBS",
    series: "Blue Label",
    madeIn: "China",
    category: "Distortion",
    additionalcategory: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 310, // in grams
    width: 6.1, // in cm
    height: 4.5, // in cm
    depth: 11, // in cm
  },
  {
    name: "Drive Me Crazy Distortion/Overdrive",
    manufacturer: "EBS",
    series: "Blue Label",
    madeIn: "China",
    category: "Distortion",
    additionalcategory: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 310, // in grams
    width: 6.1, // in cm
    height: 4.5, // in cm
    depth: 11, // in cm
  },
  {
    name: "DynaVerb",
    manufacturer: "EBS",
    madeIn: "Sweden",
    year: 2015,
    category: "Reverb",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: false,
    polarity: "Center Negative",
    circuit: "Digital",
    tubeEquipped: false,
    color: "Pink",
    weight: 400, // in grams
    specialFeatures: "Selection between 3 reverb types - Hall, Room, Plate",
    width: 7, // in cm
    height: 3.5, // in cm
    depth: 11.5, // in cm
  },
  {
    name: "MetalDrive Studio Edition",
    manufacturer: "EBS",
    series: "Studio Edition",
    madeIn: "China",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: [9, 12],
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 400, // in grams
    specialFeatures: "MOD selector for a variety of distortion sounds",
    width: 7, // in cm
    height: 3.5, // in cm
    depth: 11.5, // in cm
  },
  {
    name: "MultiComp",
    manufacturer: "EBS",
    madeIn: "Sweden",
    year: 2015,
    category: "Compressor",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "Buffered Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 400, // in grams
    width: 7.0, // in cm
    height: 3.5, // in cm
    depth: 11.5, // in cm
  },
  {
    name: "MultiDrive Studio Edition",
    manufacturer: "EBS",
    madeIn: "China",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 400, // in grams
    width: 6.1, // in cm
    height: 4.5, // in cm
    depth: 11, // in cm
    specialFeatures: "3 Modes: Tubesim/Flat/Standard",
  },
  {
    name: "Octabass",
    manufacturer: "EBS",
    madeIn: "China",
    category: "Octaver",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 310, // in grams
    width: 6.6, // in cm
    height: 4.8, // in cm
    depth: 11.4, // in cm
  },
  {
    name: "Red Twister",
    manufacturer: "EBS",
    madeIn: "Sweden",
    year: 2015,
    category: "Chorus",
    additionalcategory: "Flanger",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 400, // in grams
    width: 7, // in cm
    height: 3.5, // in cm
    depth: 11.5, // in cm
  },
  {
    name: "The Drive",
    manufacturer: "EBS",
    series: "Blue Label",
    madeIn: "China",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 300, // in grams
    width: 6.1, // in cm
    height: 4.5, // in cm
    depth: 11, // in cm
  },
  {
    name: "UniChorus Studio Edition",
    manufacturer: "EBS",
    madeIn: "China",
    category: "Chorus",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 400, // in grams
    famousUsers: ["Jeff Berlin"],
    specialFeatures: "Stereo Output",
    width: 7, // in cm
    height: 3.5, // in cm
    depth: 11.5, // in cm
  },
  {
    name: "Krankjorum",
    manufacturer: "Effesk",
    madeIn: "The Netherlands",
    category: "Fuzz",
    additionalcategory: "Noise Generator",
    type: "Pedal",
    jacksMountedOn: "One side",
    bypass: "Buffered Bypass",
    battery: false,
    voltage: 9,
    circuit: "Analog",
    tubeEquipped: false,
    weight: 350, // in g
    specialFeatures: "Pitch Shift",
    width: 6.6, // in cm
    height: 3.5, // in cm
    depth: 12.1, // in cm
  },
  {
    name: "Sonic Salvation",
    manufacturer: "Effesk",
    madeIn: "The Netherlands",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 420, // in g
    basedOnFamousModel: "Jordan Boss Tone",
    width: 7.9, // in cm
    height: 5.3, // in cm
    depth: 12.9, // in cm
  },
  {
    name: "Big Muff Op-Amp",
    manufacturer: "Electro-Harmonix",
    series: "Big Muff Compacts",
    madeIn: "USA",
    category: "Fuzz",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 640, // in g
    basedOnFamousModel: "EHX Big Muff V4",
    width: 7, // in cm
    height: 5.3, // in cm
    depth: 11.4, // in cm
  },
  {
    name: "Big Muff Pi",
    manufacturer: "Electro-Harmonix",
    category: "Fuzz",
    additionalcategory: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 700, // in g
    width: 14, // in cm
    height: 7.6, // in cm
    depth: 17.3, // in cm
  },
  {
    name: "Flatiron Fuzz",
    manufacturer: "Electro-Harmonix",
    category: "Fuzz",
    additionalcategory: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 250, // in g
    width: 7, // in cm
    height: 5.1, // in cm
    depth: 11.5, // in cm
    basedOnFamousModel: "ProCo RAT 2",
    specialFeatures: "op-amp powered",
  },
  {
    name: "Green Russian Big Muff",
    manufacturer: "Electro-Harmonix",
    category: "Fuzz",
    additionalcategory: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 250, // in g
    width: 7, // in cm
    height: 5.1, // in cm
    depth: 11.5, // in cm
    basedOnFamousModel:
      "Electro-Harmonix Sovtek Tall Font Green Russian Big Muff",
  },
  {
    name: "Hot Tubes Overdrive",
    manufacturer: "Electro-Harmonix",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: false,
    voltage: 12,
    polarity: "Proprietary PSU",
    circuit: "Analog",
    tubeEquipped: true,
    weight: 500, // in g
    width: 12, // in cm
    height: 4.7, // in cm
    depth: 18.9, // in cm
  },
  {
    name: "Memory Toy",
    manufacturer: "Electro-Harmonix",
    series: "Nano Series",
    category: "Delay",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    colour: ["Black", "Silver"],
    weight: 250, // in g
    width: 7.0, // in cm
    height: 5.4, // in cm
    depth: 11.5, // in cm
    basedOnFamousModel: "Electro-Harmonix Memory Man",
    specialFeatures: "MOD Toggle Switch",
  },
  {
    name: "Mini Q-Tron",
    manufacturer: "Electro-Harmonix",
    madeIn: "USA",
    category: "Envelope Filter",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: true,
    voltage: 9,
    polarity: "TRS",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 500, // in g
    famousUsers: "Wes Borland",
    width: 10.2, // in cm
    height: 8.9, // in cm
    depth: 12.1, // in cm
  },
  {
    name: "Nano Big Muff Pi",
    manufacturer: "Electro-Harmonix",
    category: "Fuzz",
    additionalcategory: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 250, // Weight converted from 0.25 kg to grams
    basedOnFamousModel: "Electro Harmonix Big Muff Pi",
    width: 6.2, // in cm
    height: 5, // in cm
    depth: 11, // in cm
  },
  {
    name: "OD Glove",
    manufacturer: "Electro-Harmonix",
    series: "Nano Series",
    madeIn: "USA",
    category: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    colour: "Black, Silver",
    weight: 300, // Weight converted from 0.3 kg to grams
    basedOnFamousModel: "Fulltone OCD",
    specialFeatures: "Mode Toggle Switch",
    width: 7.0, // in cm
    height: 5.4, // in cm
    depth: 11.5, // in cm
  },
  {
    name: "Small Stone V2 (1978)",
    manufacturer: "Electro-Harmonix",
    madeIn: "USA",
    year: 1978,
    category: "Chorus",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "Buffered Bypass",
    battery: true,
    voltage: 9,
    polarity: "TRS",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 400, // Weight converted from 0.4 kg to grams
    famousUsers: "Dimebag Darrell, Steven Wilson, Junkie XL",
    width: 8.5, // in cm
    height: 5.5, // in cm
    depth: 13.5, // in cm
  },
  {
    name: "Soul Food",
    manufacturer: "Electro-Harmonix",
    madeIn: "USA",
    year: "2010's",
    category: "Overdrive",
    additionalcategory: "Boost",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    colour: "Yellow",
    weight: 250, // Weight converted from 0.25 kg to grams
    basedOnFamousModel: "Klon",
    specialFeatures: "Switchable Buffer",
    width: 7, // in cm
    height: 5.4, // in cm
    depth: 11.5, // in cm
  },
  {
    name: "Triangle Big Muff",
    manufacturer: "Electro-Harmonix",
    category: "Fuzz",
    additionalcategory: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 350, // Weight converted from 0.35 kg to grams
    basedOnFamousModel: "Electro-Harmonix Big Muff Pi V1",
    width: 7, // in cm
    height: 5.3, // in cm
    depth: 11.4, // in cm
  },
  {
    name: "Pugilist Distortion",
    manufacturer: "Fender",
    madeIn: "China",
    category: "Distortion",
    type: "Pedal",
    jacksMountedOn: "Sides",
    bypass: "True Bypass",
    battery: true,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: false,
    weight: 540, // Weight converted from 0.54 kg to grams
    width: 14, // in cm
    height: 7.6, // in cm
    depth: 19, // in cm
  },
  {
    name: "Plasma Pedal",
    manufacturer: "Gamechanger Audio",
    madeIn: "Latvia",
    category: "Distortion",
    additionalcategory: "Overdrive",
    type: "Pedal",
    jacksMountedOn: "Top",
    bypass: "True Bypass",
    battery: false,
    voltage: 9,
    polarity: "Center Negative",
    circuit: "Analog",
    tubeEquipped: true,
    weight: 840, // Weight converted from 0.84 kg to grams
    width: 9.4, // in cm
    height: 7, // in cm
    depth: 14.8, // in cm
  },
];
const newKey = "imagePath";
const newValue =
  "https://res.cloudinary.com/dq4il1x1k/image/upload/v1691392292/pedalPlaceholder_rjswvn.svg";
effectPedals.forEach((pedal) => {
  pedal[newKey] = newValue;
});
console.log(effectPedals);
export default effectPedals;
